from django.db import models

# Create your models here.

class InvoiceEmitidas(models.Model):
    Estado_SAT = models.CharField(max_length=150, blank=True)
    Version = models.CharField(max_length=150, blank=True)
    Tipo = models.CharField(max_length=150, blank=True)
    Fecha_Emision = models.CharField(max_length=150, blank=True)
    Fecha_Timbrado = models.CharField(max_length=150, blank=True)
    Serie = models.CharField(max_length=150, blank=True)
    Folio = models.CharField(max_length=150, blank=True)
    UUID = models.CharField(max_length=150, blank=True)
    RFC_Receptor = models.CharField(max_length=150, blank=True)
    Nombre_Receptor = models.CharField(max_length=150, blank=True)
    UsoCFDI = models.CharField(max_length=150, blank=True)
    SubTotal  = models.CharField(max_length=150, blank=True)
    IVA_16 = models.CharField(max_length=150, blank=True)
    Total = models.CharField(max_length=150, blank=True)
    Total_Trasladados = models.CharField(max_length=150, blank=True)
    Moneda = models.CharField(max_length=150, blank=True)
    Forma_De_Pago = models.CharField(max_length=150, blank=True)
    Metodo_de_Pago = models.CharField(max_length=150, blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name="Fecha")
    
    
class InvoiceRecibidas(models.Model):
    Estado_SAT = models.CharField(max_length=150, blank=True)
    Version = models.CharField(max_length=150, blank=True)
    Tipo = models.CharField(max_length=150, blank=True)
    Fecha_Emision = models.CharField(max_length=150, blank=True)
    Fecha_Timbrado = models.CharField(max_length=150, blank=True)
    EstadoPago = models.CharField(max_length=150, blank=True)
    FechaPago = models.CharField(max_length=150, blank=True)
    Serie = models.CharField(max_length=150, blank=True)
    Folio = models.CharField(max_length=150, blank=True)
    UUID = models.CharField(max_length=150, blank=True)
    UUID_Relacion = models.CharField(max_length=150, blank=True)
    RFC_Emisor = models.CharField(max_length=150, blank=True)
    Nombre_Emisor = models.CharField(max_length=150, blank=True)
    LugarDeExpedicion = models.CharField(max_length=150, blank=True)
    RFC_Receptor = models.CharField(max_length=150, blank=True)
    Nombre_Receptor = models.CharField(max_length=150, blank=True)
    ResidenciaFiscal = models.CharField(max_length=150, blank=True)
    NumRegIdTrib = models.CharField(max_length=150, blank=True)
    UsoCFDI = models.CharField(max_length=150, blank=True)
    SubTotal = models.CharField(max_length=150, blank=True)
    Descuento= models.CharField(max_length=150, blank=True)
    Total_IEPS= models.CharField(max_length=150, blank=True)
    IVA_16 = models.CharField(max_length=150, blank=True)
    Retenido_IVA = models.CharField(max_length=150, blank=True)
    Retenido_ISR = models.CharField(max_length=150, blank=True)
    ISH = models.CharField(max_length=150, blank=True)
    Total = models.CharField(max_length=150, blank=True)
    TotalOriginal = models.CharField(max_length=150, blank=True)
    Total_Trasladados = models.CharField(max_length=150, blank=True)
    Total_Retenidos = models.CharField(max_length=150, blank=True)
    Total_LocalTrasladado = models.CharField(max_length=150, blank=True)
    Total_LocalRetenido = models.CharField(max_length=150, blank=True)
    Complemento = models.CharField(max_length=150, blank=True)
    Moneda = models.CharField(max_length=150, blank=True)
    Tipo_De_Cambio = models.CharField(max_length=150, blank=True)
    Forma_De_Pago = models.CharField(max_length=150, blank=True)
    Metodo_de_Pago = models.CharField(max_length=150, blank=True)
    NumCtaPago = models.CharField(max_length=150, blank=True)
    Condicion_de_Pago = models.CharField(max_length=150, blank=True)
    Combustible = models.CharField(max_length=150, blank=True)
    IEPS_3 = models.CharField(max_length=150, blank=True)
    IEPS_6 = models.CharField(max_length=150, blank=True)
    IEPS_7 = models.CharField(max_length=150, blank=True)
    IEPS_8 = models.CharField(max_length=150, blank=True)
    IEPS_9 = models.CharField(max_length=150, blank=True)
    IEPS_26 = models.CharField(max_length=150, blank=True)
    IEPS_30 = models.CharField(max_length=150, blank=True)
    IEPS_53 = models.CharField(max_length=150, blank=True)
    IEPS_160 = models.CharField(max_length=150, blank=True)
    Archivo_XML = models.CharField(max_length=150, blank=True)
    Direccion_Emisor = models.CharField(max_length=150, blank=True)
    Localidad_Emisor = models.CharField(max_length=150, blank=True)
    Direccion_Receptor = models.CharField(max_length=150, blank=True)
    Localidad_Receptor = models.CharField(max_length=150, blank=True)
    IVA_8 = models.CharField(max_length=150, blank=True)
    IEPS_304 = models.CharField(max_length=150, blank=True)
    IVA_Ret_6 = models.CharField(max_length=150, blank=True)
    AÑO = models.CharField(max_length=150, blank=True)
    MES_FACTURADO = models.CharField(max_length=150, blank=True)
    PROYECTO = models.CharField(max_length=150, blank=True)
    CONTABILIDAD = models.CharField(max_length=150, blank=True)
    ESTATUS_PAGO = models.CharField(max_length=150, blank=True)
    BANCO = models.CharField(max_length=150, blank=True)
    mes_pago_BANCO = models.CharField(max_length=150, blank=True)
    AÑO_PAGO_BANCO = models.CharField(max_length=150, blank=True)
    NOTAS = models.CharField(max_length=150, blank=True)
    TIPO_IVA = models.CharField(max_length=150, blank=True)
    DIOT_COEFICIENTE = models.CharField(max_length=150, blank=True)
    DIOT_IVA = models.CharField(max_length=150, blank=True)
    DIOT_BASE_16 = models.CharField(max_length=150, blank=True)
    COMPLEMENTO_DE_PAGO = models.CharField(max_length=150, blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name="Fecha")
    
class Balance(models.Model):
    Cuenta   = models.CharField(max_length=150, blank=True)
    Nombre = models.CharField(max_length=150, blank=True)
    Deudor_1 = models.CharField(max_length=150, blank=True)
    Acreedor_1 = models.CharField(max_length=150, blank=True)
    Cargos = models.CharField(max_length=150, blank=True)
    Abonos = models.CharField(max_length=150, blank=True)
    Deudor_2 = models.CharField(max_length=150, blank=True)
    Acreedor_2 = models.CharField(max_length=150, blank=True)
    Mes = models.CharField(max_length=150, blank=True)
    Año = models.CharField(max_length=150, blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name="Fecha")